- hosts: localhost
  tasks:
  - community.aws.ec2_instance_info:
      filters:
        "tag:Name": master
        instance-state-name: ["running"]
    register: ec2

  - template:
      src: "./master_ip.txt"
      #src: "{{ ec2['instances'][0]['public_ip_address'] }}"
      dest: "./roles/k8s_master1/vars/main.yml"

